<?php

namespace Database\Seeders;
use App\Models\Payment;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;

class PaymentSeeder extends Seeder{

    public function run(){
        $data = [
            [
                'customer_id' => '1',
                'platform_id' => '1',
                'username' => 'mitul_gd',
                'amount' => 100,
                'payment_id' => '111',
                'client_secret' => 'abc',
                'payment_type' => 'stripe',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '1',
                'platform_id' => '2',
                'username' => 'mitul_os',
                'amount' => 50,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '1',
                'platform_id' => '3',
                'username' => 'mitul_fp',
                'amount' => 80,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '1',
                'platform_id' => '4',
                'username' => 'mitul_up',
                'amount' => 90,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '1',
                'platform_id' => '5',
                'username' => 'mitul_mc',
                'amount' => 50,
                'payment_id' => '112',
                'client_secret' => 'abcd',
                'payment_type' => 'stripe',
                'payment_type_id' => 2,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '2',
                'platform_id' => '1',
                'username' => 'hardik_gd',
                'amount' => 100,
                'payment_id' => '222',
                'client_secret' => 'bbb',
                'payment_type' => 'stripe',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '2',
                'platform_id' => '2',
                'username' => 'hardik_os',
                'amount' => 50,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '2',
                'platform_id' => '3',
                'username' => 'hardik_fp',
                'amount' => 80,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '2',
                'platform_id' => '4',
                'username' => 'hardik_up',
                'amount' => 90,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '3',
                'platform_id' => '1',
                'username' => 'kiran_gd',
                'amount' => 100,
                'payment_id' => '333',
                'client_secret' => 'ccc',
                'payment_type' => 'stripe',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '3',
                'platform_id' => '2',
                'username' => 'kiran_os',
                'amount' => 50,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '3',
                'platform_id' => '3',
                'username' => 'kiran_fp',
                'amount' => 80,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '4',
                'platform_id' => '1',
                'username' => 'sani_gd',
                'amount' => 100,
                'payment_id' => '444',
                'client_secret' => 'ddd',
                'payment_type' => 'stripe',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '4',
                'platform_id' => '2',
                'username' => 'sani_os',
                'amount' => 50,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '4',
                'platform_id' => '3',
                'username' => 'sani_fp',
                'amount' => 80,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '4',
                'platform_id' => '4',
                'username' => 'sani_up',
                'amount' => 90,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '4',
                'platform_id' => '5',
                'username' => 'sani_mc',
                'amount' => 50,
                'payment_id' => '4444',
                'client_secret' => 'dddd',
                'payment_type' => 'stripe',
                'payment_type_id' => 2,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '5',
                'platform_id' => '1',
                'username' => 'jaydeep_gd',
                'amount' => 100,
                'payment_id' => '555',
                'client_secret' => 'eee',
                'payment_type' => 'stripe',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '5',
                'platform_id' => '2',
                'username' => 'jaydeep_os',
                'amount' => 50,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '5',
                'platform_id' => '3',
                'username' => 'jaydeep_fp',
                'amount' => 80,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '5',
                'platform_id' => '4',
                'username' => 'jaydeep_up',
                'amount' => 90,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '6',
                'platform_id' => '1',
                'username' => 'jeehal_gd',
                'amount' => 100,
                'payment_id' => '666',
                'client_secret' => 'fff',
                'payment_type' => 'stripe',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '6',
                'platform_id' => '2',
                'username' => 'jeehal_os',
                'amount' => 50,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ],
            [
                'customer_id' => '6',
                'platform_id' => '3',
                'username' => 'jeehal_fp',
                'amount' => 80,
                'payment_id' => '',
                'client_secret' => '',
                'payment_type' => 'cash',
                'payment_type_id' => 1,
                'payment_status' => 'succeeded',
                'recharge_status' => 'done',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'recharge_at' => date('Y-m-d H:i:s'),
                'created_by' => 1,
                'updated_by' => 1,
                'recharge_by' => 1
            ]
        ];
        
        foreach($data as $row){
            $payment = Payment::create([
                'customer_id' => $row['customer_id'],
                'platform_id' => $row['platform_id'],
                'username' => $row['username'],
                'amount' => $row['amount'],
                'payment_id' => $row['payment_id'],
                'client_secret' => $row['client_secret'],
                'payment_type' => $row['payment_type'],
                'payment_type_id' => $row['payment_type_id'],
                'payment_status' => $row['payment_status'],
                'recharge_status' => $row['recharge_status'],
                'created_at' => $row['created_at'],
                'updated_at' => $row['updated_at'],
                'recharge_at' => $row['recharge_at'],
                'created_by' => $row['created_by'],
                'updated_by' => $row['updated_by'],
                'recharge_by' => $row['recharge_by']
            ]);        
        }
    }
}